### ISSUE TITLE
Connect to multiple redis server with failover

### ISSUE THREAD

**Issue by phuongnd08** [amakawa/redic#8]
How would I setup redic if I want to use multiple redis servers with the possibility of failover (the one that being connected by the client went down)

**Comment by soveran** [comment]
I'm working on that right now, I may be able to release something very soon. It won't be a modification on Redic, but a different library that uses Redic.

**Comment by phuongnd08** [comment]
Awesome. I hope that library you were to mention is Ohm because it's what I'm in need right now :smile:

**Comment by phuongnd08** [comment]
@soveran I'm working on this: https://github.com/phuongnd08/redic-sentinel Could you give some reviews?

**Comment by soveran** [comment]
Excellent! I just checked it and I have some questions. You modify the `Redic` constant and also `Redic::Client`, is that needed to make it work with Ohm?

In general, it is better to use a different constant (for example, `RedicSentinel`), and design it so that internally it uses `Redic`. The reason for that is because by modifying `Redic` itself, you may get conflicts if a library wants to use `Redic` in some other way without the sentinel modifications. Ohm allows you to use any client that uses the same API as `Redic`, that is, once initialized it should reply to `call`, `queue` and `commit`.

I will review the rest later, but for now we can start thinking about that.

**Comment by soveran** [comment]
Forgot to mention _how_ to use a different client with Ohm, it goes like this:

```ruby
Ohm.redis = MyClient.new(...)
```
As long as the instance of `MyClient` responds to `call`, `queue` and `commit`, everything will work.

**Comment by phuongnd08** [comment]
Cool. I'm just not sure how could `commit` be implemented on top of thing like `redis-rb`. If we can simplify our project to just `redis-rb` rather than redic then I can focus on contribute work to `redis-sentinel` rather than fork to the new `redic-sentinel`

**Comment by phuongnd08** [comment]
Per your questions, I need to modify the Redic class to be able to pass in sentinels host and port information. The Redic::Client listen to change in sentinel to automatically reconnect and also reconnect in case of connection error (old master went off, master became slave)

**Comment by phuongnd08** [comment]
I fork my work off `redis-sentinel` so most of the logic there is just rewritten of `redis-sentinel` logics.

**Comment by scalp42** [comment]
I just saw this issue (opened one in [Ohm](https://github.com/soveran/ohm/issues/217)).

Is there any update to this issue by any chance? I remember running into the issue trying to use redis-rb with the call method.

**Comment by soveran** [comment]
This was addressed in [redisent](https://github.com/soveran/redisent).
